package action

const PLAYER_HEALTH = 100
const MONSTER_HEALTH = 100

const PLAYER_ATTACK_MIN_DMG = 5
const PLAYER_ATTACK_MAX_DMG = 10
const MONSTER_ATTACK_MIN_DMG = 9
const MONSTER_ATTACK_MAX_DMG = 13

const PLAYER_HEAL_MIN_VALUE = 10
const PLAYER_HEAL_MAX_VALUE = 20
const MONSTER_HEAL_MIN_VALUE = 9
const MONSTER_HEAL_MAX_VALUE = 13
